### ISSUE TITLE
Add support for state_id in addresses

### ISSUE THREAD

**Issue by bbuchalter** [DynamoMTL/spree_one_page_checkout#8]
Currently when collecting addresses, only the `state_name` attribute is supported. This is problematic for extensions like SpreeTaxCloud who depend on a state_id being set. I'm going to think over what's the best strategy to take here, but it would be very helpful to support Spree's country/state mappings.

**Comment by bbuchalter** [comment]
Interestingly, if you mark a country has requiring states, this validation takes care of the rest:
https://github.com/spree/spree/blob/master/core/app/models/spree/address.rb#L94

Perhaps worth some documentation?

**Comment by bbuchalter** [comment]
And a suggestion to add a check in an initializer?

```
unless Spree::Country.pluck(:states_required).all?
  # See https://github.com/DynamoMTL/spree_one_page_checkout/issues/8
  raise "In order for tax calculations to work, all countries must have states required."
end
```

**Comment by bryanmtl** [comment]
@bbuchalter Thanks for pointing this out. I would like to have support for collecting state_ids for addresses, but I'm not sure just yet the best way of handling it. 

Tax calculation is actually based on zones, which can be be made up of states or countries. The initializer would have to evaluate the zone setup and detect a possible conflict. 

Ultimately, I believe we'll need to refactor https://github.com/DynamoMTL/spree_one_page_checkout/blob/master/app/widgets/one_page_checkout/address_book/new_address/form.html.erb#L9 to behave more like https://github.com/DynamoMTL/spree_one_page_checkout/blob/master/app/widgets/one_page_checkout/address_book/new_address/form.html.erb#L9

We'll give this some thought as a part of our 2.2 upgrade. 

cc: @mickeyren @bourroush @DanielWright

**Comment by bbuchalter** [comment]
@bryanmtl thanks for taking the time to reply. I am aware the by default Spree calculates taxes by Zone, but honestly, if you're a US store, taxes are just too complicated to use Spree's default system and requires integration with a vendor like Tax Cloud.

Looking forward to integrating your work. Would you like me to close this ticket? Or shall we leave it open until we come to a more complete resolution?

**Comment by bryanmtl** [comment]
@bbuchalter I agree with you, taxes are too complicated to use the default system. My point is that the calculator that gets configured (be it Spree's default, Tax Cloud, Avalara, etc.) are based on Zones, and not countries or states. 

Ideally, we keep the extension generic enough to support international stores. I think Spree's default address form setup, while a bit ugly, is the right approach. We'll just work on improving that and see where it takes us. 

Let's keep this issue open, for now.

**Comment by bbuchalter** [comment]
@bryanmtl you're point is well taken. I think you are right on to offer maximum support. I guess more than anything, a little documentation would help people trying to wire together all these pieces of the puzzle. Having found this little surprise when integrating with tax cloud, I figured I'd share. Perhaps this GitHub issue will be documentation enough. Thanks for your attention and thoughtful replies.

**Comment by DanielWright** [comment]
@bbuchalter Apologies in advance if my answers are a bit janky. I've been off Spree projects for a hot minute.

As you've correctly sussed out, the behaviour in the address form was built with Spree's automatic conversion of `state_name` to `state_id` (where possible) in mind. It does, as you deduce, require setting `requires_state` to true on the appropriate Spree::Country records. However, I'm not sure a blanket requirement makes sense, so countries without required states don't get lumped in.

Maybe additional predicates in the initializer you propose, to check for the presence of a `state_id`-sensitive tax calculator as well as eligible countries? Along the lines of:

```
return unless defined?(SpreeAvatax) || defined?(SpreeTaxCloud)

unless Spree::Country.where(states_required: false).any? { |c| c.states.count > 0 }
  raise RuntimeError, "In order for tax calculations to work, countries with states must set states_required to true."
end
```

---

@bryanmtl OPCO was meant to be an opinionated extension, and reverting to the rabbit's warren of Spree's terrible `state_id`/`state_name` switcheroo implementation is precisely the opposite of opinionated. I think that documenting the `states_required` prerequisite is a better option. Definitely the problem here is silent failures.
